version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: subscriptions_db
      POSTGRES_USER: user_app
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/subscriptions_db
      SPRING_DATASOURCE_USERNAME: user_app
      SPRING_DATASOURCE_PASSWORD: 1234

volumes:
  pgdata:
