spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/subscriptions_db
    username: user_app
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: subscription-service
server:
  port: 8080
